-
  branches:
    only:
    - master
  
  install:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))

  before_build:
    - nuget restore "C#.Net/JDI UI Framework.sln"

  build_script: 
    - msbuild "C#.Net/JDI UI Framework.sln" /p:Configuration=Release /t:Rebuild
  
  services:
  - iis
  
  test_script:
    - nunit3-console "C#.Net/bin/Release/JDI UI Framework.dll" --noresult
